"""Add payment_id to orders

Revision ID: 094cda1253c3
Revises: ffcfde051a53
Create Date: 2025-11-20 14:45:38.923355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094cda1253c3'
down_revision = 'ffcfde051a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
