"""Rename created_at to uploaded_at in portfolio table

Revision ID: 65755d636dbd
Revises: 3deb26c16e0a
Create Date: 2026-01-15 21:40:10.355893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65755d636dbd'
down_revision = '3deb26c16e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_portfolio_created_at'))
        batch_op.create_index(batch_op.f('ix_portfolio_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_portfolio_uploaded_at'))
        batch_op.create_index(batch_op.f('ix_portfolio_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###
