"""Add full_name, phone, avatar_path, and role columns to users table

Revision ID: ad428333899d
Revises: 65755d636dbd
Create Date: 2026-01-15 21:49:24.198238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad428333899d'
down_revision = '65755d636dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
