"""empty message

Revision ID: b3a8353bb6ef
Revises: a9d30545bc8d
Create Date: 2026-01-15 21:13:20.287995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3a8353bb6ef'
down_revision = 'a9d30545bc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('quantity')
        batch_op.drop_column('price_at_order')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('booking_datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=140),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=140),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_portfolio_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('comment')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=140),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=140),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('services_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('full_name')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('username')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('services_ibfk_1'), 'categories', ['category_id'], ['id'])
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('body')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_portfolio_created_at'))
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.alter_column('booking_datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_at_order', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('price')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
